### PR TITLE
Bucket mode for variable-timing universal remote

### PR DESCRIPTION
**Pull request by rhx**
This is great work, thanks a lot!

The protocols for the remotes I have didn't work with the existing learn (A9) and universal transmit (A8) commands, because they have (in addition to sync) more than two timing combinations (e.g. tri-state).

For this, I have added a new universal transmit command B0 that allows to specify up to 16 timing brackets (including sync) that can be used for RF on (mark) and off (space).  This allows all sorts of combinations of on/off timings to be transmitted (see README.md).  I have tested this with with a number of remotes I have and it worked great.

A couple of things to note:
 - there is no learning command at the moment (and may be a bit tricky with the memory constraints), but the remotes can be learnt with a simple Arduino sketch (see README),
 - The RF_DATA buffer size is increased to accommodate longer codes and the UART buffer size is decreased (had no issues, even with very long UART commands),
 - From what I could gather, the variability exceeds what the PCA and timers can do, so at the moment, this uses a simple cycle count to control timing (but I'm no 8051 expert, so maybe there is a better way),
 - Obviously, there is no Espurna / Tasmota support at this stage yet.

### CODE REVIEW

**Comment by rhx** [comment]
I have now also added a pull request for the Espurna firmware that supports sending raw UART data, such as the 0xA8 and my 0xB0 command from this pull request:

https://bitbucket.org/xoseperez/espurna/pull-requests/43

This works very well with the tri-state remotes that I have!

**Comment by Portisch** [comment]
I think sniffing should be also possible. As because the RF signal is getting repeated first will be to find the sync (longest bucket). After this find up to 8 different buckets like RFControl. On the next repeat you will be able to decode the signal. I will do some testing in the next time.

**Comment by ciotlosm** [comment]
@rhx would it be possible to update your changes upstream here to get benefit of updates in both repositories?
Happy to help with docs or anything else.

**Comment by rhx** [comment]
Yes, happy to do this. In fact, what's in my devel branch is the same as what's in Portisch:master right now.

**Pull request merged**
